version: '3.8'
services:
  prometheus-001: &prometheus
    image: prom/prometheus:v2.24.1
    container_name: prometheus-001
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--web.external-url=http://localhost/prometheus",
        "--web.route-prefix=/",
      ]
    volumes:
      [
        "./deployment/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml",
        "./deployment/prometheus/rules.yml:/etc/prometheus/rules.yml",
      ]

  alertmanager-001: &alertmanager 
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager-001
    command:
      [
        "--config.file=/etc/alertmanager/alertmanager.yml",
        "--web.external-url=http://localhost/alertmanager",
        "--web.route-prefix=/",
      ]
    volumes:
      [
        "./deployment/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml",
      ]
    ports:
      - 8093:9093

  grafana:
    image: grafana/grafana:7.3.7
    container_name: grafana
    volumes:
      [
        "./deployment/grafana/grafana.ini:/etc/grafana/grafana.ini",
        "./deployment/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml",
      ]
  nginx:
    image: nginx:1.18.0
    container_name: nginx
    volumes:
      [
        "./deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf",
      ] 
    ports:
      - 80:80